fix bug in scrapefilters
ProjectJobsGe/jobs-ge-scrapper-nodejs pull request #10
Opened 2018-12-26 16:19 UTC by mdivani

თუ რომელიმე ფილტრზე ვაკანსიები არ იყო საერთოდ მაგ შემთხვევაში აგდებდა ერორს if statement დავამატე რომ მსგავსი შემთხვევვები გაითვალისწინოს.

2018-12-27 11:07 UTC, otarza commented
@mdivani ეხლა ესეთი პრობლემაა:

```App started!
Starting scrapping jobs
2018-12-27T10:53:50.274Z - info: [request-promise-retry] Encountered error Error: getaddrinfo ENOTFOUND jobs.ge jobs.ge:80 for undefined request to http://jobs.ge/200468/, retry count 5
2018-12-27T10:53:50.339Z - info: [request-promise-retry] Encountered error Error: getaddrinfo ENOTFOUND jobs.ge jobs.ge:80 for undefined request to http://jobs.ge/200340/, retry count 5
2018-12-27T10:53:50.413Z - info: [request-promise-retry] Encountered error Error: getaddrinfo ENOTFOUND jobs.ge jobs.ge:80 for undefined request to http://jobs.ge/200739/, retry count 5
{ Error: ENOENT: no such file or directory, open './temp/jobs.json'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1187:35)
    at getTarget.then.then.then.then (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/app/index.js:30:8)
    at tryCatcher (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Volumes/Mac 2/Develop/jobs-ge-scrapper-nodejs/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './temp/jobs.json' }
Jobs scrapped!
```

ესეთ შეცდომებს აგდებს კიდევ ბევრს: 
```2018-12-27T10:58:18.231Z - info: [request-promise-retry] Encountered error Error: read ECONNRESET for undefined request to http://jobs.ge/200597/, retry count 4
```

შემოთავაზებული გადაწყვეტები:
- მგონი ჯობია ფაილში ჩაწერა დავიკიდოთ საერთოდ, იმიტომ რომ საბოლოოდ მაინც ფაილში არ ჩაიწერება, უბრალოდ შეიძლება დააბრუნოს JSON ამ ეტაპზე და აქ მოვიდეს უბრალოდ ეგ დატა: 

```javascript
scrapeData().then((jobs) => {
  console.log('Jobs scrapped!');
  sendJobsToAPI(jobs);
});```

- თუ გაფეილდება რექვესთი და ესეთ რამეს წერს `ECONNRESET for undefined request to....` მაშინ ჯობია თავი დავანებოთ იმ კონკრეტული ლინკის პარსვას, მაგრამ სადმე შევინახოთ რომ კონკრეტულად ეს ჯობები გაფეილდა და თავიდან უნდა ვცადოთ რაღაც დროის მერე. ეს ცალკე ტასკია, ამ ეტაპზე უბრალოდ დაიკიდოს და აღარ ცადოს და დავწეროთ ამის შესაბამის ტასკი სადაც გავაკეთებთ მთლიანად სერვისის არქიტექტურას, როგორ უნდა იმუშაოს, რა ინტერვალებში, გაფეილებულებს რა უყოს და ა.შ.

2018-12-27 11:08 UTC, otarza requested changes
↑

2018-12-27 12:18 UTC, mdivani commented
> თუ გაფეილდება რექვესთი და ესეთ რამეს წერს ECONNRESET for undefined request to....

 ეს მაქვს გათვალისწინებული, ბევრი რიქუესტებია და იმიტო ფეილდება ლიმიტს ცდება როგორც ჩანს და რეტრაი მაქვს გაწერილი საბოლოო ჯამში მოაქვს მაინც ყველა ინფო, უბრალოდ ამ ერორებს აგდებს რამდენჯერაც კონკრეტულ რიქუესთზე retry ჭირდება. 

json ფაილზე ეგრე ვქნათ როგორც შენ ამბობ, უბრალოდ დემონსტრაციისთვის მინდოდა ამ ეტაპზე, ისე ეგ ერორი სავარაუდოდ იმიტოა რო temp ფოლდერი არ გაქვს ლოკალზე და უბრალოდ root-ში რო შევინახოთ იმუშავებს ყველასთან.

2018-12-28 06:25 UTC, otarza commented
@mdivani ამ ერორს რომ აგდებს:

```ECONNRESET for undefined request to....```

მერე საერთოდ ვეღარ ამთავრებს, სულ retry - ს ცდილობს და მაინც იგივე ერორზე გადის და გუშინ ნახევარ საათზე მეტი მქონდა გაშვებული და მაინც ვერ დაასრულა და ხელით გავთიშე.

ამიტო მგონია რომ ჯობია რაიმე ინტერვალი დავიცვათ, ან რიგში ჩავაყენოთ რექვესთები და ერთდროულად რაღაც რაოდენობაზე მეტი არ გავაგზავნოთ ხოლმე, ერთი რომ მორჩება მერე გავაგზავნოთ სხვა და ა.შ. მაგრამ ერთდროულად 5-6 რექვესთზე მეტი რომ არ ვაგზავნოთ წესით მოაგვარებს მაგ პრობლემას. 

ასევე როცა გაფეილდება ჯობია გაფეილებულს თავი დავანებოთ და retry აღარ ვცადოთ. უბრალოდ ჩავიწეროთ სადმე ბაზაში ან თუ გინდა ამ ეტაპზე ფაილში სადმე რომ კონკრეტულად ეს ჯობი გაფეილდა და მთლიანად რომ მორჩება ყველას მერე ბოლოს გაფეილებული ცაკლე ვცადოთ ხოლმე ვთქვათ 1-2 წუთის მერე.

2018-12-28 08:08 UTC, mdivani commented
@otarza ანუ მაგაზე ცალკე ტასკი გავაკეთოთ ხო? თან პრინციპში როცა თაიმერს გავუწერთ შეგვიძლია ისიც გავითვალისწინოთ რო ერთხელ უკვე წამოღებული ინფო შემდეგზე აღარ წამოიღოს და ეგეც საგრძნობლად შეამცირებს რიქუესტების რაოდენობას.

2018-12-28 11:41 UTC, otarza commented
@mdivani კი შეგვიძლია ცალკე ტასკი იყოს ეს.

2018-12-28 15:28 UTC, otarza approved these changes

2018-12-28 15:28 UTC, merged